name: Deploy to Netlify
on:
  push:
    branches:
      - master

jobs:
  publish_to_netlify:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./web

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install

        - name: Build React App
          run: npm run build

        - name: Deploy production to Netlify
          uses: South-Paw/action-netlify-deploy@v1.2.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
            build-dir: './web/build'